# Generated by Django 4.1.4 on 2023-01-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='name',
            new_name='sensor_name',
        ),
        migrations.RenameField(
            model_name='temperaturemeasurement',
            old_name='sensor_id',
            new_name='sensor_name',
        ),
        migrations.AlterField(
            model_name='temperaturemeasurement',
            name='measurement_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
